version: "3"
services:
  # Frontend Server
  client:
    container_name: client
    build:
      context: .
      dockerfile: client/node.Dockerfile
    environment:
      PUBLIC_API_ENDPOINT: http://127.0.0.1:5000
    image: zachtsk/recsys-client
    restart: unless-stopped
    ports:
      - 3000:3000

  # API Server
  api:
    container_name: api
    build:
      context: .
      dockerfile: prod2vec/python.Dockerfile
    image: zachtsk/recsys-api
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      CLIENT_ENDPOINT: http://127.0.0.1:3000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      RUNTIME: ${RUNTIME}
      PORT: 5000
    volumes:
      - ./prod2vec:/app
    ports:
      - 5000:5000

  # Datalake Server
  minio:
    container_name: minio
    build:
      context: .
      dockerfile: datalake/minio.Dockerfile
    image: zachtsk/recsys-s3
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - 9000:9000
      - 9001:9001