version: "3"
services:
  # API Server
  api:
    container_name: api
    build:
      context: .
      dockerfile: prod2vec/python.Dockerfile
    image: zachtsk/recsys-api
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      RUNTIME: ${RUNTIME}
      PORT: 8000

    ports:
      - 8000:8000

  # Datalake Server
  minio:
    container_name: minio
    build:
      context: .
      dockerfile: datalake/minio.Dockerfile
    image: zachtsk/recsys-s3
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - 9000:9000
      - 9001:9001